### PR TITLE
Revert f3b41e1

### PR DESCRIPTION
**Pull request by cslux**
We don't need to call `rtags-diacnostics` when company initializes the
back-ends.

Better set `rtags-autostart-diagnostics` to `t`:
``` emacs-lisp
(setq rtags-autostart-diagnostics t)
```

Otherwise `rtags-diagnostics` gets started already on emacs start-up
when `company-mode` gets enabled, this happens of course only if `company-rtags` is added to `company-backends`.

It was added due to the issue #379.

What do you think @Andersbakken

### CODE REVIEW

**Comment by Andersbakken** [comment]
rtags-diagnostics is a noop if it's already running though. This kinda requires people to already have diagnostics enabled. I personally don't use completions but it seems appropriate for them to make sure the diagnostics are running, since they otherwise do nothing at all.

**Comment by cslux** [comment]
> This kinda requires people to already have diagnostics enabled.

True, I run also into the same issue initially, but setting `rtags-autostart-diagnostics` to `t` fixed it.

**Comment by cslux** [comment]
I still think we should revert it or otherwise add something which doesn't start diagnostic on emacs start-up, just because company gets enabled. Course one could add `company-rtags` only to `company-backends` when `c-mode-/c++-mode-hook` etc. gets called, but that is another story. On the other hand if `rtags` can auto-start the diagnostics anyway it isn't really necessary though.

PS: I fixed some defcustom type missmatch

**Comment by cslux** [comment]
Hey Anders,

I fixed some type mismatch in some of the defcustom's, in addition I added the keyword `:safe ...`  where appropriate.

Let me know what you think about the changes.

Regards,
Christian

**Comment by cslux** [comment]
Regarding commit https://github.com/cslux/rtags/commit/816aef2306343c2d803e6cf25e96dbfac5a3996c, I'll use company mode, and hence, I have proved that it works without the `init` branch.

**Comment by cslux** [comment]
Ok, I also made a bit doc housekeeping.

**Comment by Andersbakken** [comment]
I think I understand the problem. You don't want init to start the diagnostics because that happens even before you try to complete. I am not sure if we should require people to have rtags-autostart-diagnostics on to have a seamless experience with rtags-company. 

I think the fix I just put in should take care of it though. Can you check? 

I'm basically not starting diagnostics in init if rtags-autostart-diagnostics is true.

**Comment by cslux** [comment]
> I think the fix I just put in should take care of it though. Can you check?

Yep, does work! Thanks

**Comment by Andersbakken** [comment]
Awesome.

Anders

**Pull request merged**
