### PR TITLE
Do not install and byte-compile elisp if emacs version is smaller tha…

### PR DESCRIPTION
**Pull request by cslux**
…n 23

### CODE REVIEW

**Comment by cslux** [comment]
Do not merge still something missing.

**Comment by cslux** [comment]
Can be merged now.

Christian

**Comment by cslux** [comment]
Reworked it once more, the logic is as follow.

If emacs was not found or emas is <23, the lisp files will not be installed, and not byte-compiled.
Since emacs is not a requirement, I thought it makes sense to not install the lisp files all together, if it wasn't found. 

Christian

**Comment by Andersbakken** [comment]
I think I like that approach. Merging now.

Anders

**Pull request merged**
