### PR TITLE
Yet another pull-request

### PR DESCRIPTION
**Pull request by cslux**
- Follow the cmake module convention for `FindXXX.cmake` https://cmake.org/cgi-bin/viewcvs.cgi/CMake/Modules/readme.txt?view=markup
- `REQUIRE` argument to find_package never worked
- Remove the `CLANG_HACK...` something from the cache, instead but `LIBCLANG_CXXFLAGS`, `LIBCLANG_LLVM_CONFIG_EXECUTABLE` and `LIBCLANG_LIBRARY` into to cache but mark them as advanced.
- Print feature summary, using the module `FeatureSummary.cmake` available since 2.8 

PS: Not sure if this is valid putting my copyright notice into the file...? You could create a CONTRIBUTORS file, in the root directory, or/and an AUTHORS file.

Further, some labels in the issue tracker would help to have a better overview what the individual reports content is about. 

My suggestion:

- whish
- bug
- question
- duplicate

What do you think?

regards,
Christian

### CODE REVIEW

**Comment by cslux** [comment]
This pull-request also contains some minor rtags.el changes.

**Comment by Andersbakken** [comment]
Me and Jan Erik used to work at Trolltech (Makers of Qt) so int was considered the size type there. I'm starting to feel like it should be size_t to get in line with everything else.

**Comment by Andersbakken** [comment]
In other words. A pull request changing it in all appropriate locations would be accepted.

**Comment by Andersbakken** [comment]
It's not just String. Pretty much all of our containers are int-based.

**Comment by cslux** [comment]
> Me and Jan Erik used to work at Trolltech (Makers of Qt) so int was considered the size type there. I'm starting to feel like it should be size_t to get in line with everything else.

Amazing, Qt is a pretty awesome framework. Never noticed that int was the size type there, but that's probably because you don't use so much the C++ headers directly, when writing applications in Qt.

> In other words. A pull request changing it in all appropriate locations would be accepted.

If it is accepted I may do it but will not be too soon, a bit busy with work and university :-/

> It's not just String. Pretty much all of our containers are int-based.

Right!

**Comment by Andersbakken** [comment]
Qt is pretty awesome (though I don't find myself using it anymore). C11 has
made some of Qt less necessary and desktop GUI applications just isn't what
I'm writing at this point. There's certainly no rush with the size_t thing.

**Pull request merged**
