### PR TITLE
Fixed travis script.

### PR DESCRIPTION
**Pull request by baol**

### CODE REVIEW

**Comment by Andersbakken** [comment]
Travis seems not like this one.

**Comment by baol** [comment]
(give me 5 min :)

**Comment by Andersbakken** [comment]
Sure thing :-)

Anders

**Comment by baol** [comment]
Fixing bash scripts without being able to run locally with a 20min feedback time is not fun! :)

Now it is good to go!

**Comment by baol** [comment]
Btw, the tests are passing now with 3 compilers and are skipped when using clang-3.6. 

They are still yellow now because Travis killed a VM while it was running, but the job passed on my branch.

Ready to be merged.

**Pull request merged**
