### PR TITLE
Running tests on travis

### PR DESCRIPTION
**Pull request by baol**
Just a try, no need to merge if not passing.

### CODE REVIEW

**Comment by Andersbakken** [comment]
I guess you actually automatically get travis output for merge requests.
Seems like it requires some switch:

https://travis-ci.org/Andersbakken/rtags/jobs/84614895

Anders

**Comment by baol** [comment]
I would like to add some tests for the rename symbol as well, but now it's a bit late :)

**Comment by baol** [comment]
10 tests passed :)

**Comment by Andersbakken** [comment]
How so? Can't you update the merge and have it run again?

Anders

**Comment by Andersbakken** [comment]
Sweet :-)

Anders

**Comment by baol** [comment]
I'm a bit new to pull requests. How one does update a merge?

**Comment by baol** [comment]
Not sure why they fail with clang 3.6 though!

**Comment by baol** [comment]
Is it working for you on clang-3.6? 
Does not seem to be an issue in the tests (even if without using hamcrest or similar tools, the error message is a bit terse)

**Comment by cslux** [comment]
@baol Do you mean squashing the commits together? If yes you would need the rebase interactively and than you would have to run `git push -f origin/master` to force the push.

**Comment by baol** [comment]
The same command is working locally with clang-3.6...

**Comment by baol** [comment]
@cslux done thanks!

**Comment by cslux** [comment]
No problem! But keep in mind, you should never ever use this approach when part of the commits are already merged with the upstream/master branch, as this could break things badly :-)

**Comment by cslux** [comment]
So I'm off it's already 4 in the morning :-D

**Comment by baol** [comment]
Umh... the tests were not run. Seems that travis uses an old 12.04... will take a while to reproduce..

**Comment by baol** [comment]
Anyway I changed the test runner for the automated tests. Now it is much shorter and it's easier to add new tests. Just add a new folder with some sources and an "expectation.json" file!

**Comment by baol** [comment]
(anyway, I need to make a few more changes)

**Comment by cslux** [comment]
Hey @baol, you could add this two lines after the imports in the test_runner.py to suppress the creation of a byte compiled python file (.pyc)
``` py
sys.dont_write_bytecode = True
os.environ["PYTHONDONTWRITEBYTECODE"] = "1"
```
regards,
christian

**Comment by baol** [comment]
Back to the start.

It seems that the rtags is not working on the travis VM using clang-3.6...

Not sure what to do. If you agree I will remove the configuration from the matrix for now. I don't think it will make any difference removing it since I believe that running the tests just highlighted a pre-existing situation.

cheers,
mirko

**Comment by cslux** [comment]
Don't forget to remove the `*.pyc` from `.gitignore` since python isn't generating a byte-compiled file anymore.

**Comment by Andersbakken** [comment]
Sounds fine to me.

Anders

**Pull request closed without merging**
