### PR TITLE
Fix unused variable warning

### PR DESCRIPTION
**Pull request by realwakka**
Fix unused variable stack & SIZE

### CODE REVIEW

**Comment by Andersbakken** [comment]
Thanks. Sorry about the delay. That's a good fix. Just out of curiosity. What platform are you hitting this on? E.g. What platform doesn't have backtrace that RTags runs on :-)

**Comment by realwakka** [comment]
I'm using rtags in FreeBSD 11 and LLVM 37 version. thanks :-)

**Comment by realwakka** [comment]
Is this just closed request without merged??

**Comment by Andersbakken** [comment]
Oops. Merged now.

**Comment by Andersbakken** [comment]
Sorry about that. I just forgot to actually hit the confirm merge button :-)

Anders

**Pull request merged**
