### PR TITLE
Some small changes, and rework of the bash-completion file.

### PR DESCRIPTION
**Pull request by cslux**
Reworked the bash-completion file. Install it when the bash-completion cmake package is present.
Create symlink's {rc,rdm} to rtags bash completion file, so bash-completion can automatically load the rtags completion file if rc or rdm requests completion.

Rename `jobcount` in RClient.cpp to job-count.

### CODE REVIEW

**Comment by Andersbakken** [comment]
Looks good to me. Thanks.

**Comment by cslux** [comment]
Just saw I forgot to declare **cur** as local in the bash completion file. 

Also would you accept an uninstall cmake script? If yes, I'll write one and adjust the minor issue in the bash completion as well! 

Chris

**Comment by Andersbakken** [comment]
Hi Christian

Sure. Uninstall would be cool. I could have sworn I replied to this already
but apparently not. I'll make cur local.

Thanks

Anders

**Comment by Andersbakken** [comment]
Shouldn't app be local as well?

Anders

**Comment by cslux** [comment]
Definitely, my bad sorry!

**Pull request merged**
