### PR TITLE
Small cmake changes.

### PR DESCRIPTION
**Pull request by cslux**
- Use different regex to get llvm cxx flags. This time the matches
  will be extracted, i.e., the include path and all `-D` something with
  the exception of `-DNDEBUG` no more not less.
- Now I understand the hole caching principles, it need to be set once,
  and if changes want be made later the usual `set` macro should be
  used. Right now the prefix path had no influence, sorry my mess :-/

### CODE REVIEW

**Comment by cslux** [comment]
Is it possible to simulate an installation on Travis too? I think so, why shouldn't it.

**Comment by cslux** [comment]
@Andersbakken gcc 4.9 seems to have bug which causes the build to fail with address-sanitizer enabled.

https://lists.debian.org/debian-gcc/2015/05/msg00156.html

but should be fixed in gcc 5.0 and above. I'll tried to replace the 4.9 compiler version 4.9 in the travis file with 5.0/5.1 but seems like it is not available in travis.

**Comment by cleeland** [comment]
Is 4.9.1 available?  I use that on our CentOS systems with asan with no
troubles and we have condition variables galore.

On Sat, Oct 24, 2015 at 6:02 AM, Christian Schwarzgruber <
notifications@github.com> wrote:

> @Andersbakken <https://github.com/Andersbakken> gcc 4.9 seems to have bug
> which causes the build to fail with address-sanitizer enabled.
>
> https://lists.debian.org/debian-gcc/2015/05/msg00156.html
>
> but should be fixed in gcc 5.0 and above. I'll tried to replace the 4.9
> compiler version 4.9 in the travis file with 5.0/5.1 but seems like it is
> not available in travis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Andersbakken/rtags/pull/482#issuecomment-150784627>.
>



-- 
Chris Cleeland

**Comment by cslux** [comment]
Unfortunately not :-/, and can't be installed without `sudo`, but in this travis environment the `sudo` comment is not allowed.

**Comment by Andersbakken** [comment]
It says something about enabling sudo from the .travis file.

Anders

**Comment by Andersbakken** [comment]
We could just disable ASAN for that build though.

Anders

**Comment by Andersbakken** [comment]
This job is running on container-based infrastructure, which does not
allow use of 'sudo', setuid and setguid executables.

If you require sudo, add 'sudo: required' to your .travis.yml

See http://docs.travis-ci.com/user/workers/container-based-infrastructure/
for details.

**Comment by Andersbakken** [comment]
I'm a little curious what asan actually thought was wrong though. I've had
good experiences with it so far. I'm running gcc 4.9.2 at home and can't
see anything. The logs seem to indicate a zero-pointer dereference but
there's no proper stack.

Anders

**Comment by cslux** [comment]
> I'm a little curious what asan actually thought was wrong though. I've had good experiences with it so far. I'm running gcc 4.9.2 at home and can't see anything. The logs seem to indicate a zero-pointer dereference but there's no proper stack.

Would be interesting for sure. Actually I didn't even know that it exists. I do not run into any issue at home either (gcc 5.1.1). I'll tried to downgrade my gcc version but due to the dependency nightmare, it's not that easy, maybe I'll compile gcc 4.9 manually.

Christian

**Comment by cleeland** [comment]
Based on the bug @cslux referenced, I would expect that whatever ASAN found it was a phantom issue.  The code referenced in the bug is completely legit code that ASAN apparently erroneously flags.

You might consider flagging the offending function to NOT be instrumented for now, or, if the function contains enough code that you want the rest instrumented, then factor out the mistakenly offending code into a separate static thusly flagged.

http://clang.llvm.org/docs/AddressSanitizer.html#disabling-instrumentation-with-attribute-no-sanitize-address

**Comment by Andersbakken** [comment]
Thanks. Looks good to me.

**Pull request merged**
