### PR TITLE
Add possibility to force bash completion installation

### PR DESCRIPTION
**Pull request by cslux**
The bash completion files can now be forced to be included in the
installation process, by setting the variable
`FORCE_BASH_COMPLETION_INSTALLATION` to `TRUE` or `ON`.
By default this variable is set to `FALSE` (`OFF`). If it set to TRUE
ignore pkg-config at all. The variable can also be set through the
interactive `ccmake` environment.

Example:

Default value of `BASH_COMPLETION_COMPLETIONSDIR` is
"/usr/share/bash-completion/completions" if installation is forced, but
can of course be overridden.

```bash
cmake -DFORCE_BASH_COMPLETION_INSTALLATION=ON
```

The value of `CMAKE_INSTALL_PREFIX` will always be the prefix of
`BASH_COMPLETION_COMPLETIONSDIR`.

### CODE REVIEW

**Comment by cslux** [comment]
@Andersbakken 

Do you know whats wrong in travis, the both clang build jobs failed for the same reason
``` bash
 curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -

curl: (7) couldn't connect to host

gpg: no valid OpenPGP data found.

The command "curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -" failed and exited with 2 during .
```

**Comment by Andersbakken** [comment]
My guess is that we need to add gnupg as an apt install thing.

Anders

**Comment by cslux** [comment]
I tried it on my Debian server, where it did succeeded successfully, so I closed the PR and reopened it, and see there it works now again, hmmm.

**Comment by Andersbakken** [comment]
I added gnupg to the travis packages which might have made it work.

**Comment by Andersbakken** [comment]
Thanks.

**Pull request merged**
