### PR TITLE
minor optmization on creting tramp temp file

### PR DESCRIPTION
**Pull request by vibrys**

### CODE REVIEW

**Comment by Andersbakken** [comment]
Hi

I honestly don't know this code that well. Why isn't the tramp-compat-make-temp-file needed here? I would expect the file to have to live on "tramp" host? If this works and indeed is faster then I'll gladly merge it. I just wanted to make sure I understood.

**Comment by vibrys** [comment]
I'm searching the reason of tramp temp file copying to remote site.
     Copying /tmp/tramp.6517C1d to /scp:remote:/tmp/tramp.6517P_j...
     ......
     ......
     Copying /tmp/tramp.6517C1d to /scp:remote:/tmp/tramp.6517P_j...done

While going through the code I initially thought the reason is the line of code which is the subject of this pull request. It is not, but this change does not seem to spoil anything (so far). I was working with this fix applied for 2 days. What is more, the reason of local (temp) file creation is that `process-file` sends file contents to remote site. Thus IMHO we do not need anything more than that, that's why the change.

**Comment by Andersbakken** [comment]
That does make sense actually.

I'll apply it and if it breaks something presumably someone will let us
know :-)

Thanks

Anders

**Comment by vibrys** [comment]
I'm also going to use this code so this should help to get an answer.

Regards,
Mat

**Comment by Andersbakken** [comment]
Sounds good.

Thanks

Anders

**Pull request merged**
