### PR TITLE
Use /usr/local as install prefix on Darwin.

### PR DESCRIPTION
**Pull request by cslux**

### CODE REVIEW

**Comment by Andersbakken** [comment]
Shouldn't the default be /usr/local: on linux too?

**Comment by cslux** [comment]
> Shouldn't the default be /usr/local: on linux too?

Right! But I changed it to /usr for the following reasons.
1) The bash completion want work by default (assuming the bash-completion package >=v1.9 is installed)
2) The rtags elisp directory is not added automatically to the emacs load-path.

But yeah, maybe that is a bit to user friendly :-/?

**Comment by Andersbakken** [comment]
Yeah. I guess that's kinda true. In a perfect world most people would
install from their package system but I guess we're not really there yet :-)

We could always change it later if it causes people problems.

Anders

**Comment by cslux** [comment]
So we remove to hole thing and leave the cmake default value /usr/local?
```
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    if(CMAKE_SYSTEM_NAME MATCHES "Darwin")
	set(CMAKE_INSTALL_PREFIX "/usr/local" CACHE PATH "Default install path" FORCE)
    else()
	set(CMAKE_INSTALL_PREFIX "/usr" CACHE PATH "Default install path" FORCE)
    endif()
endif()
```

**Comment by Andersbakken** [comment]
I think that might be the best actually.

**Comment by cslux** [comment]
True

**Pull request merged**
