### PR TITLE
Search known paths for (clang) system include dir

### LINKED ISSUE #505: Out of the box support for system clang on fedora (other distros)
The rtags clang include path [defaults](https://github.com/Andersbakken/rtags/blob/d51dedd/src/Server.cpp#L158) to `$(llvm-config --libdir)/clang/<ver>/include` which works iff the user compiled llvm manually and installed it with `--prefix=/usr`. 

In fedora, and very likely other distros, the clang include files live elsewhere. For example in fedora 23 (which provides co-existing packages for 3.3, 3.4, 3.7) the include file are installed in `/usr/lib/clang/x.y.z/include/`, while `llvm-config --libdir =>  /usr/lib64/llvm`. 

The user can always pass the proper  `-I` to `rdm` and get on with it, but figuring out what the problem is (from puzzling missing file warnings), why it is, where it is and how to fix it is a nusance.
In the interest of "just work, damnit", how about making the include path guessing a little more tenacious in trying to get the include path right?  

A possible solution would be to have a fixed list of prefixes (for llvm, fedora,debian/ubuntu, etc') that are used in turn to construct a versioned path, until an existing path is found. Just that will probably take care of the vast majority of linux users, and more paths can easily be added as users incrementally whine about their own system. 

How about it?

Previously reported in #335 but the issue (such as it is) remains.

### PR DESCRIPTION
**Pull request by PhilllyJoy**
Look under `llvm-config --libdir` first (the current default) and if the directory isn't there, try under `/usr/lib/...`. 

Tested on fedora. I've looked up the file lists for clang packages on debian and arch as well,
and this should cover all of them.

Closes #505

### CODE REVIEW

**Comment by Andersbakken** [comment]
Thanks. Merged now.

Anders

**Comment by PhilllyJoy** [comment]
Great. Thanks for cleaning up, I wasn't sure a `c++11` compiler was guaranteed.

**Comment by PhilllyJoy** [comment]
The  `#include <vector>` added can be reverted too, btw.

**Comment by Andersbakken** [comment]
Ah. Right. Thanks, and thanks for providing the fix.

Anders

**Pull request merged**
