### PR TITLE
Adding automated tests for the follow forward declaration use case.

### PR DESCRIPTION
**Pull request by baol**
Hi,
just added the tests we mentioned.

I also relaxed the comparison operator in the tests since they were failing for me due to abs/rel paths.

This tells me that those tests are there, but are not run automatically. I tried setting up a job on drone.io, but the compilers (gcc and clang) are too old.

### CODE REVIEW

**Comment by baol** [comment]
But now I see that you do have a CI :)

**Comment by Andersbakken** [comment]
:-)

We do have some travis integration (also contributed by a generous user)
but I don't think it actually runs the automated tests. If you know how to
integrate it with travis we'd really appreciate some help on this.

Anders

**Comment by baol** [comment]
Should not be difficult, can I access the jobs?

**Comment by Andersbakken** [comment]
Good question. I don't entirely know how to modify. My guess is that one
just adds a line after make in the script portion of .travis.yml

Anders

**Comment by baol** [comment]
Seems so, I'm giving it a try. Never used travis yet.

**Comment by Andersbakken** [comment]
Thanks. I'll merge any tests or attempts you might have :-)

Anders

**Pull request merged**
