### PR TITLE
enhancement #477: let rtags handle the project that sits on remote site.

### PR DESCRIPTION
**Pull request by vibrys**
<pre>

1 Contents
==================================

1.1 enhancement #477: let rtags handle the project that sits on remote site.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


1.2 Baseline: this patch does not touch current functionality, ie. rtags on local host (a.k.a local sandbox) works as before.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1.3 `sandbox` term.
~~~~~~~~~~~~~~~~~~~

  Every user@host visited from emacs is a separate sandbox.

  Example:

  user@some.host - user's sandbox on some.host. su:: - root on local
  machine sandbox. sudo:: - root on local machine sandbox.
  local sandbox  - when emacs starts it falls into this sandbox.


1.4 how to use new functionality.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  1) install rc/rdm on remote sandbox. (this also affects su::/sudo::).
  2) start rdm on remote sandbox. (this also affects su::/sudo::).
  3) run emacs.
  4) compile project on remote sandbox using rtags instrumentation.
  5) make sure that path to rc on remote host is in Your
     tramp-remote-path variable.
  6) (setq password-cache-expiry nil)  ;; helps alot.
  7) (setq rtags-tramp-enabled t)
  8) visit some project file and use rtags on that.

1.5 tests.
~~~~~~~~~~

  All C-cr commands have been tested and are *EXPECTED* to work in
  either of scenarios:
  1) local sandbox
  2) remote host (ssh family) sandbox
  3) su::/sudo:: sandbox


1.6 multiple sandboxes in the same emacs session.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Yes, it is possible, ie You can visit files that belong to two or more
  sandboxes.

  How rtags handles it? rtags query goes to that rc/rdm
  backend that sits on the same sandbox current file is from.

1.6.1 How about diagnostics process?
------------------------------------

  1. Diagnostics is not running.
  All goes transparent.

  1. Diagnostics is running.
  Those C-cr * commands that make query to rc/rdm, do the check if
  another sandbox is going to be used. If yes, then the prompt for
  changing the sandbox appears. When confirmed, diagnostics process on
  current sandbox is stopped, then started on new sandbox. Now please
  run Your command once more.

1.6.2 Although sandboxes intermixing is possible, I'd rather suggest to work with each sandbox with separate emacs process.
---------------------------------------------------------------------------------------------------------------------------

1.7 rdm backend managing for non-local sandboxes directly from rtags.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  It is not yet done, ie. for local sandbox it works as previously, but
  for non-local sandboxes I start and stop rdm by hand.


1.8 Known issues.
~~~~~~~~~~~~~~~~~

  1) non-local sandboxes case only: when going through location stack
     with C-cr [ or ], then repeating the last command with either [ or
     ], the command is *sometimes* canceled, and I end up with
     additional '[' or ']' pressed into the buffer. It happens when
     helm-org package has been evaluated. Problem has been isolated and
     is so far reported [here]. It has nothing common with rtags.

     Reason: post-command-hook invokes rtags-update-current-project,
     which in turn invokes start-file-process after 0.5s. This makes
     repeating is canceled.

     Workaround:
     * set rtags-update-current-project-timer-interval to somewhat
       larger value, (for example 3secs), thus You'll have more time to
       repeat to next location, or
     * don't evaluate helm-org

  2) non-local sandboxes case only: (happened only once) when repeating
     through location stack with C-cr [ or ], traversing is stuck at
     some location, ie. I cannot go either forward or backward.

     Reason:
     it is because nil location has somehow been stored into
     rtags-location-stack, so subsequent visit of such location causes
     traversal to stuck. As I'll meet the problem in the future I'll fix
     it.

     Workaround: none.


  [here] https://github.com/emacs-helm/helm/issues/1299


1.9 TODO.
~~~~~~~~~

  1. consider starting as many diagnostic processes as there are opened
     sandboxes. Maybe it makes sense maybe not.
  2. handle rtags-set-current-project.
  3. let rtags start/stop rdm also on remote sandboxes.
  4. When more and more tests are performed, remove rtags-tramp-enabled
     fuse.

</pre>

### CODE REVIEW

**Comment by Andersbakken** [comment]
Hi. It looks good. Thanks. I was just wondering about one thing. Shouldn't the: rtags-sandbox-check-then-run test be added to all the interactive functions (where it makes sense) rather than in the key-definition? I am not sure everyone uses the default keybindings. (I personally map some of the most important functions to standard "tags-bindings" like M-.

**Comment by vibrys** [comment]
I initially wanted to do so, but I didn't like the idea of just touching so "many" functions, which could shadow the essence of the change. On the other hand You care about all those already running rtags configurations, that will be broken if things will be left like that, so Yes, I can go this way. Should be done tomorrow.

**Comment by Andersbakken** [comment]
Cool. Great work.

Anders

**Comment by vibrys** [comment]
<pre>
1. defvar: rtags-buffer-follows-sandbox-id-match 'ask

   Tells the way current buffer follows sandbox-id in case
   match fails at a query to rc/rdm backend.

   nil - perform current query without updating diagnostics buffer.
         Diagnostics will be away from current context.
   ask - ask the user if sandbox should be changed. After 'yes',
         perform the command once more.
   t   - change the sandbox and do the command.

2. rtags-sandbox-id-matches call moved from key macro to actual functions

3. key non-bound interactive functions also enriched with sandbox-id check.

4. for non-interactive calls, sandbox-id check is not performed.
</pre>

**Comment by Andersbakken** [comment]
Thanks. Merged now.

**Comment by vibrys** [comment]
I'm happy I can participate.
Thanks for rtags, I find it very valuable.

**Comment by Andersbakken** [comment]
Glad to hear. Let me know if you have ideas for features or improvements.

Anders

**Pull request merged**
