### PR TITLE
Improvements and fix for #475

### PR DESCRIPTION
**Pull request by cslux**

### CODE REVIEW

**Comment by cleeland** [comment]
What OS is this for?  bash-completions isn't a distinct package on all but the latest debian.

In consideration of that, the cmake needs some way for the configure/build user to explicitly set the destination for installing bash completion stuff.

**Comment by cslux** [comment]
Well, this is from debian see https://bash-completion.alioth.debian.org/

**Comment by cslux** [comment]
> In consideration of that, the cmake needs some way for the configure/build user to explicitly set the destination for installing bash completion stuff.

I considered that! 

You can use `ccmake` or `cmake` itself to configure it.

**Comment by cslux** [comment]
Oh wait, that's not entirely correct, when `pkg-config` is not available no  BASH_COMPLETION_something variables will be set.

**Comment by cslux** [comment]
But we could move the lines
```
set(BASH_COMPLETION_COMPLETIONSDIR "${CMAKE_INSTALL_PREFIX}${COMPLETIONS_DIR}"
         CACHE PATH "Bash completion installation directory" FORCE)
mark_as_advanced(BASH_COMPLETION_COMPLETIONSDIR)
set(BASH_COMPLETION_FOUND TRUE)
```
out of the if statement and set a default value for the `BASH_COMPLETION_COMPLETIONSDIR` at the top of the cmake script.

**Comment by cslux** [comment]
If the system has no bash-completion support,  i.e. the bash-completion package was not installed, than I see no point in installing the completion files. Debian wheezy (old-stable) has already the `bash-completion.pc` file in it, so every other common GNU/Linux distribution will have it too.

**Comment by cleeland** [comment]
Seems like that would work. I would comment out the `mark_as_advanced` for now since there's good probability that a system may not have the package available to install.

**Comment by cslux** [comment]
I would really leave it as it is right now. This is the usual way to check if a feature can be supported or not. On the other side, people who build there software manually, for Linux/Mac in this case, can easily fulfill the requirements for this optional feature, by installing `pkg-config` and `bash-completion`. We certainly should make them aware that rtags provides bash completion scripts via the readme, and mention the requirements that are need to successfully install the bash completion script(s). Secondly, we could add something to the cmake scripts to make the feature_summary macro aware of this feature.

I removed the `mark_as_advanced` nevertheless, since it is useless when we `FORCE` to set the variable `BASH_COMPLETION_COMPLETIONSDIR`. The path can be adjusted via the `CMAKE_INSTALL_PREFIX` variable as usual.

**Comment by Andersbakken** [comment]
Thanks.

**Comment by cleeland** [comment]
Not having a `bash-completion` package is not equivalent to not having bash completion, and pkg-config is not always available even when `bash-completion` is installed as a standard package.

For example, on RHEL/CentOS systems, `bash-completion` is not a standard package; it must be installed from a separate repository. Moreover, the package does not include any pkg-config information...because pkg-config isn't a standard package for RHEL-based systems.  http://rpmfind.net/linux/rpm2html/search.php?query=pkg-config&submit=Search+...&system=&arch=

Choosing to require that bash-completion only be done and installed when pkg-config and bash-completion is present leaves out a large part of the linux ecosystem. Considering how easy it is to honor pkg-config settings if available while allowing the user to set and install, I don't see the advantage in limiting only to pkg-config.

I suppose I'll maintain my own fork if need be.

**Comment by Andersbakken** [comment]
Hi Chris

What solution would suffice for RHEL/CentOS? Could we just add a cmake
variable override and use that if set as well?

Anders

**Comment by cslux** [comment]
Sure we could do that and add a toggle for the BASH_COMPLETION_FOUND as
well at the top of the BashCompletion.cmake but set to false by default.

Will take a closer look to those distros when I'm back from work!

Chris

**Comment by cleeland** [comment]
I think using the approach Chris (other Chris--not me) suggested here (how do I refer back to specific comment?!) would work.  I'd be happy to try it.

> But we could move the lines
>
>    set(BASH_COMPLETION_COMPLETIONSDIR ${CMAKE_INSTALL_PREFIX}${COMPLETIONS_DIR}"
>             CACHE PATH "Bash completion installation directory" FORCE)
>    mark_as_advanced(BASH_COMPLETION_COMPLETIONSDIR)
>    set(BASH_COMPLETION_FOUND TRUE)
>
> out of the if statement and set a default value for the BASH_COMPLETION_COMPLETIONSDIR at the top of the cmake script.

**Comment by cslux** [comment]
> I think using the approach Chris (other Chris--not me) suggested here

Yep, will implement a variant as soon as I'm at home :-). 

> (how do I refer back to specific comment?!

Right click on the time of that specific comment you want refer too and  copy&paste the link.
 
Example:
how_to_refer_to_older_comment
https://github.com/Andersbakken/rtags/pull/476#issuecomment-150030514

regards,
the other Chris :-)

**Pull request merged**
