### PR TITLE
Fix #1071

### LINKED ISSUE #1071: rdm crashes
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [x] company-rtags.el
   - [x] helm-rtags.el
   - [x] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [x] rtags.el

### Problem description
rdm crashes when I open two git worktrees in emacs. The rdm log buffer contains:
Process rdm exited abnormally with code 1
[Server] Compilation database loading...
[Server] Compilation database loading...
[Server] Compilation database loading...

I am using rtags with commit 284697d5.
#### Expected behavior
rdm works normal

### Environment
- Your operating system:
Linux dev-debian 4.13.0-1-amd64 #1 SMP Debian 4.13.4-1 (2017-10-01) x86_64 GNU/Linux

- LLVM/Clang version:
clang version 5.0.0-+rc2-1 (tags/RELEASE_500/rc2)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

### Feature request

Describe the feature we should add to **RTags**.

### PR DESCRIPTION
**Pull request by collinjackson93**
This is not a great way to fix this issue, but it might be worth moving forward with this temporarily since it's affecting so many users. Then we can talk about a better long-term solution.

### CODE REVIEW

**Comment by collinjackson93** [comment]
I've been running this version for the past two days and haven't experienced any rdm crashes. Before this change, it would crash pretty much any time I was editing a file.

**Comment by myrgy** [comment]
endScope() on every return is very error-prone
what if add
```
struct ScopeLock {
  void lock() { beginScope(); }
  void unlock() { endScope(); }
};
```
ScopeLock scope;
std::lock_guard<ScopeLock> lock(scope);

**Comment by collinjackson93** [comment]
@myrgy Agreed. I was thinking of something similar in the second half of [this comment](https://github.com/Andersbakken/rtags/issues/1071#issuecomment-345408777). I made this PR with the hope that people could leverage it while we do a more in-depth fix of the problem because the current version of rdm crashes far too frequently.

I'll be busy for the next couple of days, so someone else may want to take over this fix. Otherwise, I'll make your proposed change when I have some time.

**Comment by Andersbakken** [comment]
Sorry about the delays. I merged the PR and refactored a little to not manually call begin/endScope. Thanks.

**Pull request merged**
