### PR TITLE
Add documentation for the systemd support.

### PR DESCRIPTION
**Pull request by juergenhoetzel**

### CODE REVIEW

**Comment by cslux** [comment]
Cool, thank you!

Christian

**Comment by MaikoID** [comment]
Hey, I'm trying following these instruction and I'm with this error:

```
$ cat ~/.config/systemd/user/rdm.socket
[Unit]
Description=RTags daemon socket

[Socket]
ListenStream=%h/.rdm

[Install]
WantedBy=multi-user.target
```

```
$ cat ~/.config/systemd/user/rdm.service
[Unit]
Description=RTags daemon

Requires=rdm.socket

[Service]
Type=simple
ExecStart=rdm -v --inactivity-timeout 300
```
`$ systemctl --user enable rdm.socket`

```
$ systemctl --user start rdm.socket
Job for rdm.socket failed. See "systemctl --user status rdm.socket" and "journalctl -xe" for details
```

`$ systemctl --user status rdm.socket
● rdm.socket - RTags daemon socket
   Loaded: loaded (/home/maiko.costa/.config/systemd/user/rdm.socket; enabled; vendor preset: enabled)
   Active: inactive (dead)
   Listen: /home/maiko.costa/.rdm (Stream)

Set 26 17:12:17 PEDCWB203078 systemd[3509]: rdm.socket: Socket service rdm.service not loaded, refusing.
Set 26 17:12:17 PEDCWB203078 systemd[3509]: Failed to listen on RTags daemon socket.
Set 26 17:13:18 PEDCWB203078 systemd[3509]: rdm.socket: Socket service rdm.service not loaded, refusing.
Set 26 17:13:18 PEDCWB203078 systemd[3509]: Failed to listen on RTags daemon socket.
Set 26 17:17:59 PEDCWB203078 systemd[3509]: rdm.socket: Socket service rdm.service not loaded, refusing.
Set 26 17:17:59 PEDCWB203078 systemd[3509]: Failed to listen on RTags daemon socket.
Set 26 17:18:46 PEDCWB203078 systemd[3509]: rdm.socket: Socket service rdm.service not loaded, refusing.
Set 26 17:18:46 PEDCWB203078 systemd[3509]: Failed to listen on RTags daemon socket.
Set 26 17:21:02 PEDCWB203078 systemd[3509]: rdm.socket: Socket service rdm.service not loaded, refusing.
Set 26 17:21:02 PEDCWB203078 systemd[3509]: Failed to listen on RTags daemon socket.
`

I'm very noob with systemd so I really don't have any clue about the error. May you help me out?

**Comment by juergenhoetzel** [comment]
> ExecStart=rdm -v --inactivity-timeout 300

You have to provide an absolute *PATH* to rdm here.

**Comment by MaikoID** [comment]
thx

**Pull request merged**
